version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - "80:80"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19941007
      POSTGRES_DB: ecommerce-backend
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
